### ISSUE TITLE
Cheat the state

### ISSUE THREAD

**Issue by Cacowned** [JeremyLikness/redux-adventure#1]
Hi, I couldn't post this as a comment on your blog somehow:

I liked the article, but I'm missing the point where the overall state is kept, since it is possible to win the game by picking up the same item over and over again (by moving back and forth between a room with an item and a room with or without an item, former speeds it up)

**Comment by JeremyLikness** [comment]
This was a good catch. The issue is in my reducers, not in the state. The rooms currently carry references to the rooms in the compass directions, and these aren't being rebuilt - so essentially when you move, you get a new copy of the "current room" but the directional rooms are old copies, so when they are swapped to be the current room the old state is introduced. I am working on a fix and will post it shortly - basically I just need to re-reference the root room on a move rather than take the object for granted.

**Comment by JeremyLikness** [comment]
OK, this is fixed. If you look at the rooms reducer, on a MOVE instead of reducing the room that is referenced by the direction, it reduces the room based on it's index in the dungeon.

**Comment by Cacowned** [comment]
Thanks for the explanation!
